# export.ps1
param()
$ErrorActionPreference = "Stop"
$PkgDir = $PSScriptRoot
$CopilotDir = "$env:USERPROFILE\.copilot"

Write-Host "=== Copilot Export ===" -ForegroundColor Cyan

# 1. copilot-instructions.md
$src = "$CopilotDir\copilot-instructions.md"
if (Test-Path $src) {
    Copy-Item $src "$PkgDir\settings\copilot-instructions.md" -Force
    Write-Host "[OK] copilot-instructions.md" -ForegroundColor Green
}

# 2. settings.json (filtered)
$src = "$CopilotDir\settings.json"
if (Test-Path $src) {
    try {
        $obj = Get-Content $src -Raw | ConvertFrom-Json
        $out = @{}
        if ($obj.allowedUrls) { $out.allowedUrls = $obj.allowedUrls }
        $out | ConvertTo-Json -Depth 5 | Set-Content "$PkgDir\settings\settings.json" -Encoding UTF8
        Write-Host "[OK] settings.json" -ForegroundColor Green
    } catch {
        Write-Host "[WARN] settings.json: $_" -ForegroundColor Yellow
    }
}

# 3. mcp-config.json -> template + .env
$src = "$CopilotDir\mcp-config.json"
if (Test-Path $src) {
    $mcp = Get-Content $src -Raw | ConvertFrom-Json

    # read actual values
    $apiKey = $mcp.mcpServers.firecrawl.env.FIRECRAWL_API_KEY
    $fsArgs = $mcp.mcpServers.filesystem.args
    $d1 = if ($fsArgs.Count -ge 3) { $fsArgs[2] } else { "C:\Users\$env:USERNAME\Desktop" }
    $d2 = if ($fsArgs.Count -ge 4) { $fsArgs[3] } else { "C:\Users\$env:USERNAME\Documents" }
    $d3 = if ($fsArgs.Count -ge 5) { $fsArgs[4] } else { "C:\Users\$env:USERNAME\Downloads" }

    # replace values with placeholders directly on the object
    $mcp.mcpServers.firecrawl.env.FIRECRAWL_API_KEY = "PLACEHOLDER_FIRECRAWL_KEY"
    $mcp.mcpServers.filesystem.args = @("-y", "@modelcontextprotocol/server-filesystem", "PLACEHOLDER_DIR1", "PLACEHOLDER_DIR2", "PLACEHOLDER_DIR3")

    $mcp | ConvertTo-Json -Depth 10 | Set-Content "$PkgDir\settings\mcp-config.template.json" -Encoding UTF8
    Write-Host "[OK] mcp-config.template.json" -ForegroundColor Green

    # write .env with actual values
    @(
        "# Auto-generated by export.ps1 - DO NOT COMMIT",
        "FIRECRAWL_API_KEY=$apiKey",
        "FILESYSTEM_DIR_1=$d1",
        "FILESYSTEM_DIR_2=$d2",
        "FILESYSTEM_DIR_3=$d3"
    ) | Set-Content "$PkgDir\.env" -Encoding UTF8
    Write-Host "[OK] .env generated" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done! Keep .env safe - do not commit to Git." -ForegroundColor Yellow
